name: Bug Report
description: Report a reproducible bug to help us improve.
labels:
  - bug
  - '🚦 status: awaiting triage'
body:
  - type: markdown
    attributes:
      value: >
        Thank you for submitting a bug report. Please add as much information as
        possible to help us reproduce.


        ### Checklist


        1. Please make sure you are using the [latest
        version](https://www.npmjs.com/org/inertiajs-revamped) of the library
        (verify by `npm ls "@inertiajs-revamped/*"`)

        2. Please check the [open issues](./?q=is%3Aissue) to ensure you are
        reporting a new issue


        ---
  - type: textarea
    id: bug_description
    attributes:
      label: Description of the bug
      description: Tell us what bug you encountered and what should have happened.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps To Reproduce
      description: Describe the steps to reproduce the issue.
      placeholder: Please write the steps in a list form
    validations:
      required: true
  - type: dropdown
    id: packages
    attributes:
      label: Affected packages
      description: >-
        If this issue is occurring on more than 1 package, select the
        appropriate packages.
      multiple: true
      options:
        - inertiajs-revamped/core
        - inertiajs-revamped/preact
        - inertiajs-revamped/react
        - inertiajs-revamped/svelte
        - inertiajs-revamped/vue
        - inertiajs-revamped/laravel
        - inertiajs-revamped/presets
    validations:
      required: true
  - type: dropdown
    id: php_version
    attributes:
      label: PHP Version
      description: Output of `php -v`
      options:
        - '8.3'
        - '8.2'
        - '8.1'
    validations:
      required: true
  - type: dropdown
    id: _laravel_version
    attributes:
      label: Laravel Version
      description: Output of `php artisan --version`
      options:
        - v11.0.7
        - v11.0.6
        - v11.0.5
        - v11.0.4
        - v11.0.3
        - v11.0.2
        - v11.0.1
        - v11.0.0
        - v10.3.3
        - v10.3.2
        - v10.3.1
        - v10.3.0
        - v10.2.10
        - v10.2.9
        - v10.2.8
        - v10.2.7
        - v10.2.6
        - v10.2.5
        - v10.2.4
        - v10.2.3
        - v10.2.2
        - v10.2.1
        - v10.2.0
        - v10.1.1
        - v10.1.0
        - v10.0.7
        - v10.0.6
        - v10.0.5
        - v10.0.4
        - v10.0.3
        - v10.0.2
        - v10.0.1
        - v10.0.0
        - v9.5.2
        - v9.5.1
        - v9.5.0
        - v9.4.1
        - v9.4.0
        - v9.3.12
        - v9.3.11
        - v9.3.10
        - v9.3.9
        - v9.3.8
        - v9.3.7
        - v9.3.6
        - v9.3.5
        - v9.3.4
        - v9.3.3
        - v9.3.2
        - v9.3.1
        - v9.3.0
        - v9.2.1
        - v9.2.0
        - v9.1.10
        - v9.1.9
        - v9.1.8
        - v9.1.7
        - v9.1.6
        - v9.1.5
        - v9.1.4
        - v9.1.3
        - v9.1.2
        - v9.1.1
        - v9.1.0
        - v9.0.1
        - v9.0.0
    validations:
      required: true
  - type: dropdown
    id: _node_version
    attributes:
      label: Node Version
      description: Output of `node -v`
      options:
        - 22.1.0
        - 22.0.0
        - 21.7.3
        - 21.7.2
        - 21.7.1
        - 21.7.0
        - 21.6.2
        - 21.6.1
        - 21.6.0
        - 21.5.0
        - 21.4.0
        - 21.3.0
        - 21.2.0
        - 21.1.0
        - 21.0.0
        - 20.13.0
        - 20.12.2
        - 20.12.1
        - 20.12.0
        - 20.11.1
        - 20.11.0
        - 20.10.0
        - 20.9.0
        - 20.8.1
        - 20.8.0
        - 20.7.0
        - 20.6.1
        - 20.6.0
        - 20.5.1
        - 20.5.0
        - 20.4.0
        - 20.3.1
        - 20.3.0
        - 20.2.0
        - 20.1.0
        - 20.0.0
        - 19.8.1
        - 19.8.0
        - 19.7.0
        - 19.6.1
        - 19.6.0
        - 19.5.0
        - 19.4.0
        - 19.3.0
        - 19.2.0
        - 19.1.0
        - 19.0.1
        - 19.0.0
        - 18.20.2
        - 18.20.1
        - 18.20.0
        - 18.19.1
        - 18.19.0
        - 18.18.2
        - 18.18.1
        - 18.18.0
        - 18.17.1
        - 18.17.0
        - 18.16.1
        - 18.16.0
        - 18.15.0
        - 18.14.2
        - 18.14.1
        - 18.14.0
        - 18.13.0
        - 18.12.1
        - 18.12.0
    validations:
      required: false
