name: Deploy Docs

on:
  workflow_dispatch:

  push:
    branches: [main]
    paths: ['docs/**']

permissions:
  contents: read

env:
  NPM_VERSION: 21.7.2

jobs:
  deploy:
    name: Deploy Docs
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup PNPM
        uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
        # Install version depends on package.json `packageManager` field

      - name: Setup Node.js
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version: ${{ env.NPM_VERSION }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Run build
        run: pnpm run build:docs

      - name: Deploy to Server
        uses: burnett01/rsync-deployments@3cccb6851148e6198ed9ed89eb0d1c17b5e58cc7 # 7.0.2
        with:
          switches: -avzr --delete
          path: "./docs/dist/*"
          remote_path: ${{ secrets.REMOTE_PATH }}
          remote_host: ${{ secrets.FTP_SERVER }}
          remote_user: ${{ secrets.FTP_USERNAME }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
