name: Issue Labeler

on:
  issues:
    types: [opened]

permissions:
  contents: read

jobs:
  label-issues-policy:
    name: Issue Labeler
    runs-on: ubuntu-latest
    permissions:
      issues: write

    strategy:
      matrix:
        template: [bug_report.yml, feature_request.yml]

    steps:
      - name: Checkout code
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3

      - name: Parse issue form
        uses: stefanbuck/github-issue-parser@1e5bdee70d4b3e066a33aa0669ab782943825f94 # v3.1.0
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/${{ matrix.template }}

      - name: Set labels based on policy
        uses: redhat-plumbers-in-action/advanced-issue-labeler@e4a460ced9df70bb9dbd5cbd82c302d04c91c813 # v3.1.0
        with:
          issue-form: ${{ steps.issue-parser.outputs.jsonString }}
          template: ${{ matrix.template }}
          token: ${{ secrets.GITHUB_TOKEN }}
