name: Issue Labeler

on:
  issues:
    types: [opened]

permissions:
  contents: read

jobs:
  label-issues-policy:
    name: Issue Labeler
    runs-on: ubuntu-latest
    permissions:
      issues: write

    strategy:
      matrix:
        template: [bug_report.yml, feature_request.yml]

    steps:
      - name: Checkout code
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5

      - name: Parse issue form
        uses: stefanbuck/github-issue-parser@44b9b37b3fbcc7948af192ff51e3db4d5c6103ca # v3.1.1
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/${{ matrix.template }}

      - name: Set labels based on policy
        uses: redhat-plumbers-in-action/advanced-issue-labeler@d498805e5c7c0658e336948b3363480bcfd68da6 # v3.2.0
        with:
          issue-form: ${{ steps.issue-parser.outputs.jsonString }}
          template: ${{ matrix.template }}
          token: ${{ secrets.GITHUB_TOKEN }}
