name: Build Workflow

on:
  workflow_dispatch:

  push:
    branches: [main]

  pull_request:
    branches: [main]

  merge_group:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

env:
  NPM_VERSION: '21.7.2'
  # renovate: datasource=npm depName=pnpm versioning=npm
  PNPM_VERSION: '9.1.0'

jobs:
  skip-check:
    name: Skip check
    continue-on-error: true
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      should_skip: ${{ steps.skip-check.outputs.should_skip }}
    permissions:
      actions: write
      contents: read
    steps:
      - id: skip-check
        uses: fkirc/skip-duplicate-actions@f75f66ce1886f00957d99748a42c724f4330bdcf # v5.3.1
        with:
          do_not_skip: '["schedule", "workflow_dispatch"]'
          paths_ignore: |-
            [
              "**/CHANGELOG.md",
              "**/LICENSE",
              "**/README.md",
              "packages/laravel",
              "packages/presets"
            ]
          paths: |-
            [
              ".github/workflows/node-ci.yml",
              "packages/**",
              "package.json",
              "pnpm-lock.yaml"
            ]
          skip_after_successful_duplicate: false

  node-ci:
    name: Node.js CI
    needs: skip-check
    if: ${{ needs.skip-check.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 45

    steps:
      - name: Checkout code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - name: Set up PNPM
        uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Set up Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: ${{ env.NPM_VERSION }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Run build
        run: pnpm run build

      - name: Run test
        run: pnpm run test:run
        if: always()
