name: CI/CD Build Workflow

on:
  workflow_dispatch:

  push:
    branches: [main]

  pull_request:
    branches: [main]

  merge_group:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

env:
  NPM_VERSION: 21.7.2

jobs:
  skip-check:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
      paths_result: ${{ steps.skip_check.outputs.paths_result }}
    permissions:
      actions: write
      contents: read

    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@f75f66ce1886f00957d99748a42c724f4330bdcf # v5.3.1
        with:
          do_not_skip: '["schedule", "workflow_dispatch"]'
          paths_ignore: '["**/CHANGELOG.md", "**/LICENSE", "**/README.md"]'
          paths_filter: |
            core:
              paths: '["packages/core/**", "integration/core/**"]'
            react:
              paths: '["packages/react/**", "e2e/apps/react/**", "e2e/tests/**"]'
            vue:
              paths: '["packages/vue/**", "e2e/apps/vue/**", "e2e/tests/**"]'
          # We want to skip only concurrent runs. Subsequent runs/retries should be allowed.
          skip_after_successful_duplicate: false

  core:
    needs: skip-check
    if: needs.skip-check.outputs.should_skip != 'true' && needs.skip-check.outputs.paths_result.core.should_skip != 'true'
    name: Core Package CI
    runs-on: ubuntu-latest
    env:
      CI: true
    permissions:
      contents: write
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup PNPM
        uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
        # Install version depends on package.json `packageManager` field

      - name: Setup Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: ${{ env.NPM_VERSION }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Run build
        run: pnpm run build

      - name: Run integration test
        run: pnpm run test

  react:
    needs: skip-check
    if: needs.skip-check.outputs.should_skip != 'true' && needs.skip-check.outputs.paths_result.react.should_skip != 'true'
    name: React Package CI
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.45.0-jammy
    env:
      CI: true
      HOME: /root
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup PNPM
        uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
        # Install version depends on package.json `packageManager` field

      - name: Setup Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: ${{ env.NPM_VERSION }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Run build
        run: pnpm run build

      - name: Run e2e test
        run: 'pnpm run test:react'

  vue:
    needs: skip-check
    if: needs.skip-check.outputs.should_skip != 'true' && needs.skip-check.outputs.paths_result.vue.should_skip != 'true'
    name: Vue Package CI
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.45.0-jammy
    env:
      CI: true
      HOME: /root
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup PNPM
        uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
        # Install version depends on package.json `packageManager` field

      - name: Setup Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: ${{ env.NPM_VERSION }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Run build
        run: pnpm run build

      - name: Run e2e test
        run: 'pnpm run test:vue'

  # `build-result` is a workaround to skipped matrix jobs in `build` not being considered "successful",
  # which can block PR merges if matrix jobs are required status checks.
  # More info: https://github.com/fkirc/skip-check#how-to-use-skip-check-with-required-matrix-jobs
  build-result:
      name: Build Result
      if: needs.skip-check.outputs.should_skip != 'true' && always()
      runs-on: ubuntu-latest
      needs:
          - skip-check
          - core
          - react
          - vue
      steps:
          - name: Mark result as failed
            if: needs.core.result != 'success' || needs.react.result != 'success' || needs.vue.result != 'success'
            run: exit 1
