name: Laravel Adapter

on:
  workflow_dispatch:

  push:
    branches: [main]

  pull_request:
    branches: [main]

  merge_group:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  php-ci:
    name: PHP CI
    defaults:
      run:
        working-directory: ./packages/laravel
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        php: ['8.1', '8.2', '8.3']
        laravel: [9.*, 10.*, 11.*]
        stability: ['prefer-stable']
        include:
          - laravel: 9.*
            testbench: ^7.0
          - laravel: 10.*
            testbench: ^8.0
          - laravel: 11.*
            testbench: ^9.0
        exclude:
          - laravel: 10.*
            php: 8.0
          - laravel: 11.*
            php: 8.1
    permissions:
      contents: write
    timeout-minutes: 45

    steps:
      - id: skip-check
        uses: fkirc/skip-duplicate-actions@f75f66ce1886f00957d99748a42c724f4330bdcf # v5.3.1
        continue-on-error: true
        with:
          do_not_skip: '["schedule", "workflow_dispatch"]'
          paths_ignore: |-
            [
              "**/CHANGELOG.md",
              "**/LICENSE",
              "**/README.md"
            ]
          paths: |-
            [
              ".github/workflows/php-ci.yml",
              "packages/laravel/**"
            ]
          skip_after_successful_duplicate: false

      - name: Checkout code
        if: ${{ steps.skip-check.outputs.should_skip != 'true' }}
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5

      - name: Setup PHP
        if: ${{ steps.skip-check.outputs.should_skip != 'true' }}
        uses: shivammathur/setup-php@c665c7a15b5295c2488ac8a87af9cb806cd72198 # 20.30.4
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: none
  
      - name: Composer-cache
        if: ${{ steps.skip-check.outputs.should_skip != 'true' }}
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        if: ${{ steps.skip-check.outputs.should_skip != 'true' }}
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ matrix.stability }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-${{ matrix.stability }}-
      
      - name: Setup problem matchers
        if: ${{ steps.skip-check.outputs.should_skip != 'true' }}
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"
          
      - name: Install dependencies
        if: ${{ steps.skip-check.outputs.should_skip != 'true' }}
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: Run test
        if: ${{ steps.skip-check.outputs.should_skip != 'true' }}
        run: vendor/bin/phpunit
